config/routes.rb
VikingTown::Application.routes.draw do
  resources :sacrifices, except: [:destroy, :delete, :edit, :update]

  delete "fjord/abandon/:id",    :controller => :fjord,      :action => :abandon
  delete "village/abandon/:id",  :controller => :village,    :action => :abandon
  delete "fleets/remove/:id",    :controller => :fleets,     :action => :remove
  delete "fleets/:id",           :controller => :fleets,     :action => :disband

  get    "fleets",               :controller => :fleets,     :action => :list
  get    "fleets/show/:id",      :controller => :fleets,     :action => :show,     as: :fleet
  get    "fjord/list/:page",     :controller => :fjord,      :action => :list
  get    "fjord/list",           :controller => :fjord,      :action => :list
  get    "fjord/mine/:page",     :controller => :fjord,      :action => :mine
  get    "fjord/mine",           :controller => :fjord,      :action => :mine
  get    "fjord/show/:id",       :controller => :fjord,      :action => :show
  get    "home/index",           :controller => :home,       :action => :index
  get    "village/show/:id",     :controller => :village,    :action => :show
  get    "sacrifices/show/:id",  :controller => :sacrifices, :action => :show

  post   "fleets/assemble",      :controller => :fleets,     :action => :assemble, as: :new_fleet
  post   "fjord/settle",         :controller => :fjord,      :action => :settle
  post   "fjord/update",         :controller => :fjord,      :action => :update
  post   "village/found",        :controller => :village,    :action => :found
  post   "village/update",       :controller => :village,    :action => :update
  post   "villager/allocate",    :controller => :villager,   :action => :allocate
  post   "building/build/:id",   :controller => :building,   :action => :build
  
  put    "building/assign/:id",  :controller => :building,   :action => :assign
  put    "fleets/add",           :controller => :fleets,     :action => :add

  devise_for :users
  root :to => "home#index", :controller => :home, :action => :index
end

app/models/fleet.rb
class Fleet < ActiveRecord::Base
  include Resources

  has_many :ships
  belongs_to :user
  belongs_to :village

  before_destroy { |record| record.ships.update_all(fleet_id: nil) }
  
  def docked?
    not self.docked_at.blank?
  end

  def dock_at(village)
    self.village = village
    self.docked_at = Time.now
  end

  def dock_at!(village)
    self.dock_at(village)
    self.save
  end
end

app/controllers/fleets_controller.rb
class FleetsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_fleet, only: [:show, :disband, :add, :remove]

  def list
    @fleets = current_user.fleets.load
  end

  def show ; end

  def assemble
    @fleet = Fleet.new(params[:fleet])

    if @fleet.save
      redirect_to url_for(action: :show,  id: @fleet.id, controller: :fleets),
                  notice: 'Fleet was successfully created.'
    else
      render action: 'new'
    end
  end

  def add
    ship = current_user.ships.find(params[:ship_id])
    @fleet.ships << ship
    redirect_to @fleet, notice: 'Ship added'
  rescue
    ship_not_found!
  end

  def remove
    ship = current_user.ships.find(params[:ship_id])
    ship.fleet_id = nil
    ship.save
    redirect_to @fleet, notice: 'Ship removed'
  rescue
    ship_not_found!
  end

  def disband
    @fleet.destroy
    redirect_to fleets_url, notice: 'Fleet was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fleet
      @fleet = current_user.fleets.find(params[:id])
    end

    def ship_not_found!
      redirect_to @fleet, flash: { error: 'Ship not found' }
    end
end

app/helpers/fleets_helper.rb
module FleetsHelper
end

app/views/fleets/_form.html.erb
<%= form_for(@fleet) do |f| %>
  <% if @fleet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fleet.errors.count, "error") %> prohibited this fleet from being saved:</h2>

      <ul>
      <% @fleet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fleets/edit.html.erb
<h1>Editing fleet</h1>

<%= render 'form' %>

<%= link_to 'Show', @fleet %> |
<%= link_to 'Back', fleets_path %>

app/views/fleets/list.html.erb
<h1>Listing fleets</h1>

<table>
  <thead>
    <tr>
      <th>Ship</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @fleets.each do |fleet| %>
      <tr>
        <td><%= fleet.ships.count %></td>
        <td><%= link_to 'Show', fleet %></td>
        <td><%= link_to 'Disband', fleet, method: :delete, action: :disband, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fleet', new_fleet_path %>

app/views/fleets/new.html.erb
<h1>New fleet</h1>

<%= render 'form' %>

<%= link_to 'Back', fleets_path %>

app/views/fleets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fleet:</strong>
  <% @fleet.ships.each do |ship| %>
    <%= ship.awesome_inspect %>
  <% end %>
</p>

<%= link_to 'Back', fleets_path %>